name: Flutter CI/CD

on:
  push:
    branches:
      - ganna
  pull_request:
    branches:
      - ganna

jobs:
  build:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 4: Run tests
    - name: Run tests
      run: flutter test

    # Step 5: Build the app
    - name: Build APK
      run: flutter build apk --release

    # Step 6: Debugging: List APK directory
    - name: List APK directory
      run: ls -R build/app/outputs/flutter-apk/

    # Step 7: Archive build artifacts
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk